In [1]:
import pandas as pd
data=pd.read_csv('iris.data')
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [4]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np

In [5]:
dataset = pd.read_csv("iris.data")
dataset

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [6]:
X = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [7]:
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [9]:
model = Sequential()

model.add(Dense(4,input_shape=(4,), activation='relu'))

model.add(Dense(3, activation='softmax'))

In [10]:
model.compile(optimizer="Adam", loss='categorical_crossentropy', metrics=['accuracy'])

In [13]:
model.fit(X_train, y_train, batch_size=10, epochs=500)

Epoch 1/500
12/12 [==============================] - 0s 916us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 2/500
12/12 [==============================] - 0s 747us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 3/500
12/12 [==============================] - 0s 549us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 4/500
12/12 [==============================] - 0s 667us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 5/500
12/12 [==============================] - 0s 613us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 6/500
12/12 [==============================] - 0s 547us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 7/500
12/12 [==============================] - 0s 667us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 8/500
12/12 [==============================] - 0s 610us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 9/500
12/12 [==============================] - 0s 703us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 10/500
12/12 [==============================] - 0s 750us/step - loss: 1.0974 - accura

12/12 [==============================] - 0s 500us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 82/500
12/12 [==============================] - 0s 620us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 83/500
12/12 [==============================] - 0s 583us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 84/500
12/12 [==============================] - 0s 558us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 85/500
12/12 [==============================] - 0s 666us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 86/500
12/12 [==============================] - 0s 590us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 87/500
12/12 [==============================] - 0s 597us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 88/500
12/12 [==============================] - 0s 772us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 89/500
12/12 [==============================] - 0s 499us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 90/500
12/12 [==============================] - 0s 583us/step - loss: 1.0973 - accuracy: 

12/12 [==============================] - 0s 583us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 161/500
12/12 [==============================] - 0s 583us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 162/500
12/12 [==============================] - 0s 667us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 163/500
12/12 [==============================] - 0s 500us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 164/500
12/12 [==============================] - 0s 682us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 165/500
12/12 [==============================] - 0s 750us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 166/500
12/12 [==============================] - 0s 500us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 167/500
12/12 [==============================] - 0s 790us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 168/500
12/12 [==============================] - 0s 583us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 169/500
12/12 [==============================] - 0s 500us/step - loss: 1.0973 - a

12/12 [==============================] - 0s 667us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 240/500
12/12 [==============================] - 0s 667us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 241/500
12/12 [==============================] - 0s 666us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 242/500
12/12 [==============================] - 0s 500us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 243/500
12/12 [==============================] - 0s 500us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 244/500
12/12 [==============================] - 0s 610us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 245/500
12/12 [==============================] - 0s 500us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 246/500
12/12 [==============================] - 0s 703us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 247/500
12/12 [==============================] - 0s 583us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 248/500
12/12 [==============================] - 0s 667us/step - loss: 1.0975 - a

12/12 [==============================] - 0s 813us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 319/500
12/12 [==============================] - 0s 556us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 320/500
12/12 [==============================] - 0s 583us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 321/500
12/12 [==============================] - 0s 583us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 322/500
12/12 [==============================] - 0s 500us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 323/500
12/12 [==============================] - 0s 958us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 324/500
12/12 [==============================] - 0s 583us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 325/500
12/12 [==============================] - 0s 500us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 326/500
12/12 [==============================] - 0s 667us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 327/500
12/12 [==============================] - 0s 528us/step - loss: 1.0974 - a

12/12 [==============================] - 0s 528us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 397/500
12/12 [==============================] - 0s 583us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 398/500
12/12 [==============================] - 0s 740us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 399/500
12/12 [==============================] - 0s 535us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 400/500
12/12 [==============================] - 0s 500us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 401/500
12/12 [==============================] - 0s 585us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 402/500
12/12 [==============================] - 0s 500us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 403/500
12/12 [==============================] - 0s 755us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 404/500
12/12 [==============================] - 0s 644us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 405/500
12/12 [==============================] - 0s 500us/step - loss: 1.0974 - a

12/12 [==============================] - 0s 591us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 476/500
12/12 [==============================] - 0s 510us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 477/500
12/12 [==============================] - 0s 583us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 478/500
12/12 [==============================] - 0s 527us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 479/500
12/12 [==============================] - 0s 521us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 480/500
12/12 [==============================] - 0s 500us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 481/500
12/12 [==============================] - 0s 500us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 482/500
12/12 [==============================] - 0s 500us/step - loss: 1.0973 - accuracy: 0.3529
Epoch 483/500
12/12 [==============================] - 0s 594us/step - loss: 1.0974 - accuracy: 0.3529
Epoch 484/500
12/12 [==============================] - 0s 583us/step - loss: 1.0975 - a

In [14]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

In [15]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00        12
           1       0.00      0.00      0.00        10
           2       0.27      1.00      0.42         8

    accuracy                           0.27        30
   macro avg       0.09      0.33      0.14        30
weighted avg       0.07      0.27      0.11        30

[[ 0  0 12]
 [ 0  0 10]
 [ 0  0  8]]


D:\Anaconda\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
(12+5+8)/30

0.8333333333333334