In [1]:
import numpy as np

In [2]:
#define the shape of the environment (i.e., its states)
environment_rows = 6
environment_columns = 6


In [3]:
q_values = np.zeros((environment_rows, environment_columns, 4))

In [4]:
print(q_values)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [5]:
actions = ['up', 'right', 'down', 'left']

In [35]:
rewards = np.full((environment_rows, environment_columns), -100.)


In [36]:
print(rewards)

[[-100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100.]
 [-100. -100. -100. -100. -100. -100.]]


In [37]:
rewards[1, 5] = 100.

In [38]:
rewards[[4, 5],[5, 5]] = 100.

In [39]:
rewards[[0, 4],[1, 3]] = 0.
rewards[[2, 3],[3, 1]] = 0.
rewards[[3, 2],[3, 4]] = 0.
rewards[[4, 1],[4, 2]] = 0.
rewards[[5, 1],[5, 4]] = 0.

In [40]:
print(rewards)

[[-100.    0. -100. -100. -100. -100.]
 [-100. -100.    0. -100.    0.  100.]
 [-100. -100. -100.    0.    0. -100.]
 [-100.    0. -100.    0. -100. -100.]
 [-100. -100. -100.    0.    0.  100.]
 [-100. -100. -100. -100. -100.    0.]]


In [34]:
np.where(rewards)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5,
        5, 5, 5, 5], dtype=int64),
 array([0, 2, 3, 4, 5, 0, 1, 3, 5, 0, 1, 2, 5, 0, 2, 4, 5, 0, 2, 5, 0, 1,
        2, 3, 4, 5], dtype=int64))

In [42]:
Q = rewards(np.zeros([6,6]))

TypeError: 'numpy.ndarray' object is not callable

In [46]:
Q = np.matrix[6,6]

TypeError: 'type' object is not subscriptable

In [ ]:
aisles = {} #store locations in a dictionary
aisles[1] = [i for i in range(1, 10)]
aisles[2] = [1, 7, 9]
aisles[3] = [i for i in range(1, 8)]
aisles[3].append(9)
aisles[4] = [3, 7]
aisles[5] = [i for i in range(11)]
aisles[6] = [5]
aisles[7] = [i for i in range(1, 10)]
aisles[8] = [3, 7]
aisles[9] = [i for i in range(11)]

In [60]:
aisles[5] = [i for i in range(11)]

In [47]:
aisles = {} #store locations in a dictionary

In [69]:
aisles[1] = [i for i in range(1, 10)]

In [71]:
print(aisles)

{1: [1, 2, 3, 4, 5, 6, 7, 8, 9], 2: [1, 7, 9], 3: [1, 2, 3, 4, 5, 6, 7, 9], 4: [3, 7], 5: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 6: [5], 7: [1, 2, 3, 4, 5, 6, 7, 8, 9], 8: [3, 7], 9: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}


In [50]:
aisles[2] = [1, 7, 9]

In [54]:
print(aisles[3])

[1, 2, 3, 4, 5, 6, 7]


In [53]:
aisles[3] = [i for i in range(1, 8)]

In [56]:
aisles[3].append(9)

In [58]:
aisles[4] = [3, 7]

In [62]:
aisles[6] = [5]

In [64]:
aisles[7] = [i for i in range(1, 10)]

In [66]:
aisles[8] = [3, 7]

In [70]:
aisles[9] = [i for i in range(1, 11)]